name: GitHub for Publishers
description: GitHub For Publishers
meta_description: "GitHub For Publishers"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /Github-for-Publishers
domain_name: 'http://yourblog-domain.com'
google_analytics: '<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66584520-1', 'auto');
  ga('send', 'pageview');

</script>'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Cheryl Tolentino'
authorTwitter:  'cheryltino'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
